### ISSUE TITLE
Inside EditText

### ISSUE THREAD

**Issue by ren545457803** [orhanobut/dialogplus#103]
If i add a EditText into DialogPlus,then,
click editText -> pop soft keyboard -> click hardware BACK.
I want DailogPlus dismiss,but whole activity finished.
Is it a trouble?

Exp: your demo R.layout.content ,replace TextView with EditText

**Comment by orhanobut** [comment]
Yes, it's a bug which I recently faced as well. I'll try to find a solution for this. It happens when the dialog is displayed from fragment

**Comment by Deepanshwad** [comment]
Any solution for this issue? Its urgent.
Thanks in advance.

**Comment by ren545457803** [comment]
My way is that let Activity and Dialog coordinate.

One:  In Dialog holder class contain method check Dialog status.
   eg: class SMSCodeGet {
     static SMSCodeGet CODE_GET;// instance
     DialogPlus dialogPlus;
     public static boolean onBackPress() {
         if (CODE_GET != null && CODE_GET.isShowing()) {// if dialog is showing ,close
              CODE_GET.close();
              return true;
         }
         return false;
     }
}

Two: In Actvity'onBackPress call method onBackPress of SMSCodeGet.
     eg:  @Override public void onBackPressed() {
     if (SMSCodeGet.onBackPress()) {// if SMSCOdeGet consume backEvent, return
       return;
     }
     super.onBackPressed();
  }

**Comment by blackbbc** [comment]
Just add these codes to your activity
```
   @Override
    public void onBackPressed() {
        if (dialog.isShowing()) {
            dialog.dismiss();
        } else {
            super.onBackPressed();
        }
    }
```

**Comment by orhanobut** [comment]
There are some workarounds that is shown. For now I'll close this issue and re-open if this is still an issue in order to track it better.

**Comment by ashanajackol** [comment]
How to read/get value entered in the editText after pressing submit (or any button) button? Its very helpful if some can share little code snap with this :)
