### ISSUE TITLE
How to show dialog plus from Service

### ISSUE THREAD

**Issue by nguyencongbinh** [orhanobut/dialogplus#116]
I show DialogPlus from Service and the app is crashed with log : 
`mypackagename.services.TodoService cannot be cast to android.app.Activity`

**`DialogPlus dialog = DialogPlus.newDialog(context) // crash here`**

How can I pass a Activity context to Service to make dialog work ?
Please help.

**Comment by Kisty** [comment]
If you want to show it when the app is running, try registering an ActivityLifecycleListener in your service on your application (`getApplication()`) and keeping track of the current visible Activity, you can then show the activity in the current showing activity by getting last activity called in he onActivityResumed() callback.

https://developer.android.com/reference/android/app/Application.html#registerActivityLifecycleCallbacks(android.app.Application.ActivityLifecycleCallbacks)

**Comment by orhanobut** [comment]
Closing this issue. @Kisty answer seems reasonable.
