### ISSUE TITLE
OverlayBackground doesn't expand to status bar?

### ISSUE THREAD

**Issue by microstudent** [orhanobut/dialogplus#118]
Sorry to bother you.
When I use DialogPlus to show my own dialog, I found that the status bar color wouldn't be darker while A Normal AlertDialog does! And because of that, the dialog look so strange. 
Is this normal?
What if I want to darker the status bar color ? :)

**Comment by TakuSemba** [comment]
any update on this?

**Comment by TakuSemba** [comment]
I feel the same

**Comment by liuhuiAndroid** [comment]
I feel the same

**Comment by sagarmaiyad** [comment]
Any update on this issue?
