### ISSUE TITLE
How to set height and width of the dialog ?

### ISSUE THREAD

**Issue by Nitin-Daddikar** [orhanobut/dialogplus#120]
When i open the dialog it showing me full screen... It does not look good in my case... Is there any way to set height and width ?

**Comment by saeed-rz** [comment]
you can use .SetContentWidth and .SetContentHeight method
also if u want use expanded feature. use setExpanded(true,desireHeight)

**Comment by orhanobut** [comment]
Above answer should be good 👍 Closing this issue.
