### ISSUE TITLE
I am ready to use three consecutive dialog ,if i were konw threre is an animation  300ms !!!!

### ISSUE THREAD

**Issue by guoq1** [orhanobut/dialogplus#126]
I am ready to use three consecutive pop-up dialog, select the end of the first dialog, but always the second shells do not come out, and later found out that there is a 300ms disappear animation effects, it is recommended to improve the author

**Comment by looa** [comment]
You can use custom exit and enter animations. So you can control the animation time.

**Comment by Xenero** [comment]
Get over yourself @guoq1 

This isn't an issue and people like you shouldn't be opening issues for opinion matters.

**Comment by orhanobut** [comment]
Closing this issue since animations can be set.
