### ISSUE TITLE
Scrollable TextView inside DialogPlus

### ISSUE THREAD

**Issue by nachogarrone** [orhanobut/dialogplus#128]
Tried to put a scrollable TextView inside a Dialog, but i can't scroll the textView. Is there an easy configuration to solve that? 
Or should I somehow detect touch on the dialog and handle them manually?

**Comment by orhanobut** [comment]
Unfortunately this is a very difficult topic unless you want to use without `expandable=true`. With custom view and `expandable=false` it should work, otherwise a very custom solution is needed. Closing this one for now since can't do that much customization.
