### ISSUE TITLE
How to Set setOnClickListener  for Header 

### ISSUE THREAD

**Issue by Pavicool** [orhanobut/dialogplus#141]
I'm Unable to set  OnClickListner for Header ,as given in documentation  not work for me help please .

**Comment by Pavicool** [comment]
got it, by using this  sample of code  globle click is possible thank u  nice documentation 👍 
.setOnClickListener(new OnClickListener() {
    @Override
    public void onClick(DialogPlus dialog, View view) {

    }
})

**Comment by orhanobut** [comment]
👍 Awesome. Closing the issue.
