### ISSUE TITLE
Logo proposals

### ISSUE THREAD

**Issue by michaelizer** [orhanobut/dialogplus#153]
Hello, I just made a few possible variations for a logo you may want to use for your project. Tell me if you liked and I'll send the files in a pr

![dialogplus](https://user-images.githubusercontent.com/35619342/38595281-dc9e5220-3d18-11e8-96a8-3e62e0f7e063.png)

**Comment by orhanobut** [comment]
Awesome 👍 Blue one in the first row looks great! Would be good to have it in a PR definitely.

**Comment by orhanobut** [comment]
Thank you for PR, definitely appreciate it. I added the logo in README file. Therefore closing this for now.
