### ISSUE TITLE
L animation

### ISSUE THREAD

**Issue by orhanobut** [orhanobut/dialogplus#26]
It will be cool to have L animation, when the dialog is at the bottom, scrolling from bottom to top would stretch the dialog to whole screen

**Comment by AndroidDeveloperLB** [comment]
You mean like the share dialog? If so, that's what I'd like too.

**Comment by doyonghoon** [comment]
interesting. what if just putting a transparency view on the header of listview as big as vertically half of the screen size and it enables to scroll from bottom to top at any time. In addition, there would be a sticky-headerview that does like a headerview but only sticks at the top of the screen when the scroll is covered entire screen. It's inspired from the Google Keep, there is list of apps to share where is found at one's todo.

**Comment by AndroidDeveloperLB** [comment]
@doyonghoon Actually, this is possible, but maybe it would be better to search in Android's code?
I've tried searching for this in the Android's code, but couldn't find it.
Looking at the view hirerchy , this is what I've found:

![untitled20150328124438](https://cloud.githubusercontent.com/assets/5357526/6880548/4687e3a4-d548-11e4-9cdb-83c3b0f1858c.png)

The TextView is for the title of the share dialog, btw.

**Comment by AndroidDeveloperLB** [comment]
Searching for the "resolver_list" in the resources I've found this file "platforms\android-22\data\res\layout/resolver_list.xml" : 

	<com.android.internal.widget.ResolverDrawerLayout
		xmlns:android="http://schemas.android.com/apk/res/android"
		android:layout_width="match_parent"
		android:layout_height="match_parent"
		android:maxWidth="@dimen/resolver_max_width"
		android:maxCollapsedHeight="192dp"
		android:maxCollapsedHeightSmall="56dp"
		android:id="@id/contentPanel">

		<LinearLayout
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:layout_alwaysShow="true"
			android:elevation="8dp"
			android:background="@color/white" >
			<TextView android:id="@+id/title"
					  android:layout_width="0dp"
					  android:layout_height="wrap_content"
					  android:layout_weight="1"
					  android:minHeight="56dp"
					  android:textAppearance="?attr/textAppearanceMedium"
					  android:gravity="start|center_vertical"
					  android:paddingStart="?attr/dialogPreferredPadding"
					  android:paddingEnd="?attr/dialogPreferredPadding"
					  android:paddingTop="8dp"
					  android:paddingBottom="8dp" />
			<LinearLayout android:id="@+id/profile_button"
						  android:layout_width="wrap_content"
						  android:layout_height="48dp"
						  android:layout_marginTop="4dp"
						  android:layout_marginEnd="4dp"
						  android:paddingStart="8dp"
						  android:paddingEnd="8dp"
						  android:paddingTop="4dp"
						  android:paddingBottom="4dp"
						  android:focusable="true"
						  android:visibility="gone"
						  style="?attr/borderlessButtonStyle">
				<ImageView android:id="@+id/icon"
						   android:layout_width="24dp"
						   android:layout_height="24dp"
						   android:layout_gravity="start|center_vertical"
						   android:layout_marginStart="4dp"
						   android:layout_marginEnd="16dp"
						   android:layout_marginTop="12dp"
						   android:layout_marginBottom="12dp"
						   android:scaleType="fitCenter" />
				<TextView android:id="@id/text1"
						  android:layout_width="wrap_content"
						  android:layout_height="wrap_content"
						  android:layout_gravity="start|center_vertical"
						  android:layout_marginEnd="16dp"
						  android:textAppearance="?attr/textAppearanceButton"
						  android:textColor="?attr/textColorPrimary"
						  android:minLines="1"
						  android:maxLines="1"
						  android:ellipsize="marquee" />
			</LinearLayout>
		</LinearLayout>

		<ListView
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:id="@+id/resolver_list"
			android:clipToPadding="false"
			android:scrollbarStyle="outsideOverlay"
			android:background="@color/white"
			android:elevation="8dp"
			android:nestedScrollingEnabled="true"
			android:divider="@null" />

		<TextView android:id="@+id/empty"
				  android:layout_width="match_parent"
				  android:layout_height="match_parent"
				  android:layout_alwaysShow="true"
				  android:text="@string/noApplications"
				  android:padding="32dp"
				  android:gravity="center"
				  android:visibility="gone" />

		<LinearLayout
			android:id="@+id/button_bar"
			android:visibility="gone"
			style="?android:attr/buttonBarStyle"
			android:layout_width="match_parent"
			android:layout_height="wrap_content"
			android:layout_ignoreOffset="true"
			android:layout_alwaysShow="true"
			android:gravity="end|center_vertical"
			android:orientation="horizontal"
			android:layoutDirection="locale"
			android:measureWithLargestChild="true"
			android:background="@color/white"
			android:paddingTop="8dp"
			android:paddingBottom="8dp"
			android:paddingStart="12dp"
			android:paddingEnd="12dp"
			android:elevation="8dp">
			<Button android:id="@+id/button_once"
					android:layout_width="wrap_content"
					android:layout_gravity="start"
					android:maxLines="2"
					style="?android:attr/buttonBarNegativeButtonStyle"
					android:minHeight="@dimen/alert_dialog_button_bar_height"
					android:layout_height="wrap_content"
					android:enabled="false"
					android:text="@string/activity_resolver_use_once"
					android:onClick="onButtonClick" />
			<Button android:id="@+id/button_always"
					android:layout_width="wrap_content"
					android:layout_gravity="end"
					android:maxLines="2"
					android:minHeight="@dimen/alert_dialog_button_bar_height"
					style="?android:attr/buttonBarPositiveButtonStyle"
					android:layout_height="wrap_content"
					android:enabled="false"
					android:text="@string/activity_resolver_use_always"
					android:onClick="onButtonClick" />
		</LinearLayout>

	</com.android.internal.widget.ResolverDrawerLayout>

**Comment by doyonghoon** [comment]
@AndroidDeveloperLB so let me explain what I've achieved so far. The classes that you mentioned, [ResolverDrawerLayout](https://github.com/android/platform_frameworks_base/blob/master/core/java/com/android/internal/widget/ResolverDrawerLayout.java) and [ResolverActivity](https://github.com/android/platform_frameworks_base/blob/master/core/java/com/android/internal/app/ResolverActivity.java) is not publicly accessible since it is unfortunately used only in the Google Android team. However, I copied whole codes related with `ResolverActivity` from [lolipop_code_base](https://github.com/android/platform_frameworks_base) and it has been eventually reproduced.

As you expect, two parts are divided into to create this feature, list of apps to share. 

  * First part is a dimmed screen that covered at top of the screen. There are lots of attributes used to resemble closely `Dialog`, those attrs enable to create dimmed screen part such as `android:windowIsTranslucent`. Also intro animations are covered in this part.
  * Second part is an interation that scrolling from bottom to top, stretching the dialog to whole screen. The `ResolverDrawerLayout` is utilized for stretching to whole screen and list on share-apps are items on `ListView`.

I'm worried to cover this feature(scrolling from bottom to top, streching to whole screen) in DialogPlus since the way to create it may be quite different from the original one. `DialogPlus` is locked in only `Dialog`, however this feature is an `Activity`. I think we need to customize it as `View` to adopt it into `DialogPlus`, There could be a painful efforts to reproduce it. How do you guys think of it? @AndroidDeveloperLB @orhanobut

thanks.

![sample](https://s3-ap-northeast-1.amazonaws.com/doyonghoon/drawer_list.gif)

**Comment by AndroidDeveloperLB** [comment]
@doyonghoon Well, maybe it's best to try it on various device configurations, including tablets and landscape orientation. 
This way you could see if it really works the same way, or differently on some cases.

**Comment by doyonghoon** [comment]
@AndroidDeveloperLB Let me dive into how to adopt it into `DialogPlus` and let me give some suggestions for it. I think `ScreenType` is a key point that let enable this feature. There should be a new type of enum value that describes covering only half of the screen when `DialogPlus` enters on window, even if there are enough items to cover whole screen. `ResolverDrawerLayout` will be mandatory to create scrolling from bottom to top, eventually stretching the dialog to whole screen.

@orhanobut mind if I create a pull request for this issue and you point out if there are parts to improve? thanks.

**Comment by AndroidDeveloperLB** [comment]
@doyonghoon Sorry, I didn't dive enough to be of any help.

**Comment by orhanobut** [comment]
@doyonghoon @AndroidDeveloperLB First of all thanks for discussing about this feature. Currently I didn't have enough time to cover this feature but I'll be happy if you make a pull request of course. We can discuss the implementation and make it smooth and proper together.  :+1:

**Comment by orhanobut** [comment]
This feature is added since v1.6
