### ISSUE TITLE
Can't import for some reason

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [orhanobut/dialogplus#28]
all I see is this:

![untitled20150308202354](https://cloud.githubusercontent.com/assets/5357526/6546976/1a4d5304-c5d1-11e4-87a3-8148cfa94c1e.png)

I tried looking at "help"->"show log", but there is no "show log" there .

**Comment by orhanobut** [comment]
you can add an empty credential.properties for the time being to avoid getting this error. I'll add a solid solution soon for this.

**Comment by orhanobut** [comment]
I also changed the gradle file. Can you try again by pulling the new changes?

**Comment by AndroidDeveloperLB** [comment]
I don't understand what you mean by "add an empty credential.properties", but I've re-imported the project and it seems like it works now.

How come other people succeeded importing the project, while I didn't?

**Comment by orhanobut** [comment]
L animation is still on progress, an issue is created for this animation. It will be added soon.

**Comment by AndroidDeveloperLB** [comment]
what animation?
I'm talking about the sharing dialog. if you scroll it from bottom->top, it gets larger till it covers the whole screen.

**Comment by orhanobut** [comment]
that's why I was talking about

**Comment by orhanobut** [comment]
that's what I was talking about it. Couldn't edit the previous comment from phone

**Comment by AndroidDeveloperLB** [comment]
oh ok. thank you for this cool library. if you wish, you can look at my libraries too:
https://github.com/AndroidDeveloperLB?tab=repositories

**Comment by orhanobut** [comment]
Thanks! I'll certainly check it out your repos
