### ISSUE TITLE
(NullpointerException) Hardware acceleration issue on older Android versions

### ISSUE THREAD

**Issue by JesperLR** [orhanobut/dialogplus#31]
DialogPlus has an issue on older Android versions (I tested on an Incredible S running 4.0.4).

Gives the following exception:
 java.lang.NullPointerException
            at android.view.GLES20RecordingCanvas.drawPatch(GLES20RecordingCanvas.java:97)...

Can be solved by changing line 256 in the DialogPlus class from:
decorView.removeView(rootView);

to:

decorView.post(new Runnable() {
                    @Override
                    public void run() {
                        decorView.removeView(rootView);
                    }
                });

**Comment by orhanobut** [comment]
@JesperLR thank you for the feedback, I'll check it out asap

**Comment by orhanobut** [comment]
with the new release this issue should be fixed. v1.4
