### ISSUE TITLE
Callback when the dialog has been dismissed

### ISSUE THREAD

**Issue by doyonghoon** [orhanobut/dialogplus#33]
As Ordinary Dialog does, DialogPlus seems like to have the listener that notifies the user when DialogPlus dismisses. mind if I push a pull request for this issue and review for my code? thanks.

**Comment by orhanobut** [comment]
@doyonghoon Of course you can, It will be good to have it.

**Comment by doyonghoon** [comment]
@orhanobut thanks for quick reply. I just tried to push a pull request for this issue, I encountered an error. here is the message.
```fatal: unable to access 'https://github.com/orhanobut/dialogplus.git/': The requested URL returned error: 403```

To solve this problem, i think that you may add me as a contributor or something in this project.

**Comment by orhanobut** [comment]
To contribute, you need to fork the project and then you can push it to the your origin. then you can create a pull request from that point.

**Comment by doyonghoon** [comment]
aha, got it. thanks.

**Comment by doyonghoon** [comment]
solved issue.
