### ISSUE TITLE
Option to handle Back key

### ISSUE THREAD

**Issue by Euphrates-Media** [orhanobut/dialogplus#36]
It would be nice to have an option to consume Back key event and don't pass it to rest of activity.

**Comment by orhanobut** [comment]
@Euphrates-Media That's a very good idea.

**Comment by orhanobut** [comment]
With v1.5, OnBackPressListener added, but still needs a trick. OnBackPressListener will be always triggered whether it is cancelable or not. Thus you can use cancelable=false and trigger the event.
