### ISSUE TITLE
How to change view contents in ViewHolder?

### ISSUE THREAD

**Issue by mikeng13** [orhanobut/dialogplus#37]
Hey guys,

When using the viewholder, how do I get a hold of the view so that I can make changes to the textview and imageview properties inside of that view?

**Comment by orhanobut** [comment]
There is no option for that but it should be certainly there.

**Comment by rizhilee** [comment]
I slove like this.
        LayoutInflater layoutInflater = getLayoutInflater();
        View layout = layoutInflater.inflate(R.layout.layout_publish_et, (ViewGroup) findViewById(R.id.layout_publish_et));
        Holder holder = new ViewHolder(layout);
 final EditText etTitle = (EditText)layout.findViewById(R.id.et_send_title);
,maybe it can help you.

**Comment by orhanobut** [comment]
With the new release (v1.5), you can use
```java
getHolderView();  returns the holder view as listview,gridview or your custom view
getFooterView();
getHeaderView();
```

**Comment by mikeng13** [comment]
Awesome! Thanks!
