### ISSUE TITLE
Error while using inflated view

### ISSUE THREAD

**Issue by Euphrates-Media** [orhanobut/dialogplus#38]
When I try to set ViewHolder to an inflated view, I receive this error and nothing is displayed :

My code :

<code>
View view = mInflater.inflate(R.layout.my_popup, null, false);

        Display display = getWindowManager().getDefaultDisplay();
        Point size = new Point();
        display.getSize(size);
        int height = size.y;
        RelativeLayout.LayoutParams params = new RelativeLayout.LayoutParams(RelativeLayout.LayoutParams.FILL_PARENT, (int) (height * .75));
        params.addRule(RelativeLayout.ALIGN_PARENT_BOTTOM);
        view.setLayoutParams(params);

        WebView webView = (WebView) view.findViewById(R.id.webView);
        WebSettings settings = webView.getSettings();
        settings.setDefaultTextEncodingName("utf-8");
        webView.setScrollContainer(false);

        webView.loadDataWithBaseURL(null, sample_dictionary_html, "text/html", "utf-8", null);
        dialog_plus = new DialogPlus.Builder(this)
                .setContentHolder(new ViewHolder(view))

                .create();
        dialog_plus.show();
</code>

MY ERROR :warning: 

<code>
04-04 12:06:41.839    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ java.lang.RuntimeException: Don't call setOnClickListener for an AdapterView. You probably want setOnItemClickListener instead
04-04 12:06:41.839    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at android.widget.AdapterView.setOnClickListener(AdapterView.java:926)
04-04 12:06:41.839    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus.setClickListener(DialogPlus.java:413)
04-04 12:06:41.839    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus.assignClickListenerRecursively(DialogPlus.java:402)
04-04 12:06:41.839    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus.assignClickListenerRecursively(DialogPlus.java:399)
04-04 12:06:41.839    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus.assignClickListenerRecursively(DialogPlus.java:399)
04-04 12:06:41.839    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus.assignClickListenerRecursively(DialogPlus.java:399)
04-04 12:06:41.839    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus.assignClickListenerRecursively(DialogPlus.java:399)
04-04 12:06:41.839    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus.createView(DialogPlus.java:361)
04-04 12:06:41.839    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus.initContentView(DialogPlus.java:286)
04-04 12:06:41.844    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus.createDialog(DialogPlus.java:276)
04-04 12:06:41.844    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus.<init>(DialogPlus.java:168)
04-04 12:06:41.844    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus.<init>(DialogPlus.java:18)
04-04 12:06:41.844    4282-4282/com.daftar.Abrar.Interface W/System.err﹕ at com.orhanobut.dialogplus.DialogPlus$Builder.create(DialogPlus.java:666)
</code>

**Comment by orhanobut** [comment]
I'll provide a solution for this in this weekend. I think I know why it happens. Just need to confirm

**Comment by orhanobut** [comment]
This is fixed with v1.5
