### ISSUE TITLE
OnItemClickListener is not working.

### ISSUE THREAD

**Issue by sandeep-agrawal** [orhanobut/dialogplus#41]
I am trying below code in my activity but is not calling the click listener.

    DialogPlus dialogPlus = new DialogPlus.Builder(MainActivity.this)
                        .setAdapter(new SimpleAdapter(MainActivity.this,false))
                        .setOnClickListener(new OnClickListener() {
                            @Override
                            public void onClick(DialogPlus dialog, View view) {
                                dialog.dismiss();
                            }
                        })
                        .setOnItemClickListener(new OnItemClickListener() {
                            @Override
                            public void onItemClick(DialogPlus dialog, Object item, View view, int position) {
                                dialog.dismiss();
                            }
                        })
                        .create();
                dialogPlus.show();

Am I doing anything wrong?

**Comment by orhanobut** [comment]
onCLickListener is redundant here but rest should work, but I don't see any list inside simpleadapter. Can you take a screenshot of the dialogplus in the app and show the whole code?

**Comment by orhanobut** [comment]
I think the problem is solved
