### ISSUE TITLE
Center does not work on horizontal axis

### ISSUE THREAD

**Issue by ergunkocak** [orhanobut/dialogplus#47]
Hi,

First of all tnx very much for such clean and developer friendly library :)

As you can be seen in attachment i could not center on horizontal axis. Does library support this functionality or did i miss something?

Here is my code : 

    final DialogPlus dialog = new DialogPlus.Builder(this)
                .setOnItemClickListener(new OnItemClickListener() {
                    @Override
                    public void onItemClick(DialogPlus dialog, Object item, View view, int position) {
                        //
                    }
                })
                .setGravity(DialogPlus.Gravity.CENTER)
                .setContentHolder(isparkDetailView)
                .setCancelable(true)
                .create();
    dialog.show();

![screenshot-2015-06-18_15 23 07 964](https://cloud.githubusercontent.com/assets/610975/8231050/51090742-15ce-11e5-9ad9-70027086b9d9.png)

King Regards

**Comment by orhanobut** [comment]
Hey, thank you!

Can you show the xml file? It should use the whole width as default

**Comment by ergunkocak** [comment]
Thanks for fast response,

I added another linear layout to center the content and solved the problem but tapping outside of the box on right and left side does not close the box now because there is an invisible container :) 

Here is the problematic version before i applied temporary container addition : 

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="match_parent"
    android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
    android:layout_height="wrap_content"
    android:layout_gravity="center">


    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text=""
        android:id="@+id/ispark_detail_name"
        android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
        android:layout_gravity="center_horizontal" />

    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
        android:layout_gravity="center_horizontal">

        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
            android:layout_gravity="center_horizontal">

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".3"
                android:layout_height="wrap_content"
                android:text="@string/ispark_detail_label_opening"
                android:id="@+id/ispark_label_opening"
                android:textColor="@color/isparkDetailLabelText"
                android:singleLine="true"
                android:layout_marginRight="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="end"
                android:layout_gravity="center_horizontal" />

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".7"
                android:layout_height="wrap_content"
                android:text=""
                android:id="@+id/ispark_detail_opening"
                android:textColor="@color/isparkDetailText"
                android:singleLine="true"
                android:layout_marginLeft="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="start"
                android:layout_gravity="center_horizontal" />

        </LinearLayout>

        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
            android:layout_gravity="center_horizontal">

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".3"
                android:layout_height="wrap_content"
                android:text="@string/ispark_detail_label_closing"
                android:id="@+id/ispark_label_closing"
                android:textColor="@color/isparkDetailLabelText"
                android:singleLine="true"
                android:layout_marginRight="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="end"
                android:layout_gravity="center_horizontal" />

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".7"
                android:layout_height="wrap_content"
                android:text=""
                android:id="@+id/ispark_detail_closing"
                android:textColor="@color/isparkDetailText"
                android:singleLine="true"
                android:layout_marginLeft="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="start"
                android:layout_gravity="center_horizontal" />

        </LinearLayout>

        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
            android:layout_gravity="center_horizontal">

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".3"
                android:layout_height="wrap_content"
                android:text="@string/ispark_detail_label_capacity"
                android:id="@+id/ispark_label_capacity"
                android:textColor="@color/isparkDetailLabelText"
                android:singleLine="true"
                android:layout_marginRight="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="end"
                android:layout_gravity="center_horizontal" />

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".7"
                android:layout_height="wrap_content"
                android:text=""
                android:id="@+id/ispark_detail_capacity"
                android:textColor="@color/isparkDetailText"
                android:singleLine="true"
                android:layout_marginLeft="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="start"
                android:layout_gravity="center_horizontal" />

        </LinearLayout>

        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
            android:layout_gravity="center_horizontal">

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".3"
                android:layout_height="wrap_content"
                android:text="@string/ispark_detail_label_location"
                android:id="@+id/ispark_label_location"
                android:textColor="@color/isparkDetailLabelText"
                android:singleLine="true"
                android:layout_marginRight="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="end"
                android:layout_gravity="center_horizontal" />

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".7"
                android:layout_height="wrap_content"
                android:text=""
                android:id="@+id/ispark_detail_address"
                android:textColor="@color/isparkDetailText"
                android:singleLine="false"
                android:layout_marginLeft="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="start"
                android:layout_gravity="center_horizontal" />

        </LinearLayout>

    </LinearLayout>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
        android:text=""
        android:singleLine="false"
        android:id="@+id/ispark_detail_location"
        android:layout_gravity="center_horizontal" />

    <LinearLayout
        android:orientation="horizontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material">

        <RelativeLayout
            android:id="@+id/relativeLayout1"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material">

            <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="@string/close"
                android:layout_alignParentLeft="true"
                android:id="@+id/ispark_detail_cancel"
                android:textColor="@color/isparkDetailButtonCloseText"
                android:background="@android:color/transparent" />

            <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true"
                android:text="@string/ispark_detail_route"
                android:id="@+id/ispark_detail_route"
                android:textColor="#FFF"
                android:background="@color/isparkDetailButtonBgActive" />

        </RelativeLayout>

    </LinearLayout>

</LinearLayout>

**Comment by orhanobut** [comment]
I'll check it out this issue.

**Comment by orhanobut** [comment]
does the issue still exists with 1.6 version?

**Comment by ergunkocak** [comment]
I was using : 

compile 'com.orhanobut:dialogplus:1.6@aar'

**Comment by orhanobut** [comment]
Can you try with v1.8? Although that should work out of box with the previous version as well.

**Comment by ergunkocak** [comment]
Very busy with another project. i will check asap

**Comment by ergunkocak** [comment]
I just recompiled with 1.7 and worked. I tried with 1.6 and did not work so i think it is fixed in 1.7.
Could not try with 1.8 or 1.9 because there seems many changes occured :)

Gradle:

    compile 'com.orhanobut:dialogplus:1.7@aar'

Layout:

    <?xml version="1.0" encoding="utf-8"?>
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="vertical"
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
    android:background="@color/white_color"
    android:layout_gravity="center">

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text=""
        android:id="@+id/ispark_detail_name"
        android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
        android:layout_gravity="center_horizontal" />

    <LinearLayout
        android:orientation="vertical"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
        android:layout_gravity="center_horizontal">

        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
            android:layout_gravity="center_horizontal">

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".3"
                android:layout_height="wrap_content"
                android:text="@string/ispark_detail_label_opening"
                android:id="@+id/ispark_label_opening"
                android:textColor="@color/isparkDetailLabelText"
                android:singleLine="true"
                android:layout_marginRight="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="end"
                android:layout_gravity="center_horizontal" />

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".7"
                android:layout_height="wrap_content"
                android:text=""
                android:id="@+id/ispark_detail_opening"
                android:textColor="@color/isparkDetailText"
                android:singleLine="true"
                android:layout_marginLeft="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="start"
                android:layout_gravity="center_horizontal" />

        </LinearLayout>

        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
            android:layout_gravity="center_horizontal">

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".3"
                android:layout_height="wrap_content"
                android:text="@string/ispark_detail_label_closing"
                android:id="@+id/ispark_label_closing"
                android:textColor="@color/isparkDetailLabelText"
                android:singleLine="true"
                android:layout_marginRight="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="end"
                android:layout_gravity="center_horizontal" />

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".7"
                android:layout_height="wrap_content"
                android:text=""
                android:id="@+id/ispark_detail_closing"
                android:textColor="@color/isparkDetailText"
                android:singleLine="true"
                android:layout_marginLeft="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="start"
                android:layout_gravity="center_horizontal" />

        </LinearLayout>

        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
            android:layout_gravity="center_horizontal">

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".3"
                android:layout_height="wrap_content"
                android:text="@string/ispark_detail_label_capacity"
                android:id="@+id/ispark_label_capacity"
                android:textColor="@color/isparkDetailLabelText"
                android:singleLine="true"
                android:layout_marginRight="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="end"
                android:layout_gravity="center_horizontal" />

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".7"
                android:layout_height="wrap_content"
                android:text=""
                android:id="@+id/ispark_detail_capacity"
                android:textColor="@color/isparkDetailText"
                android:singleLine="true"
                android:layout_marginLeft="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="start"
                android:layout_gravity="center_horizontal" />

        </LinearLayout>

        <LinearLayout
            android:orientation="horizontal"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
            android:layout_gravity="center_horizontal">

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".3"
                android:layout_height="wrap_content"
                android:text="@string/ispark_detail_label_location"
                android:id="@+id/ispark_label_location"
                android:textColor="@color/isparkDetailLabelText"
                android:singleLine="true"
                android:layout_marginRight="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="end"
                android:layout_gravity="center_horizontal" />

            <TextView
                android:layout_width="0dp"
                android:layout_weight=".7"
                android:layout_height="wrap_content"
                android:text=""
                android:id="@+id/ispark_detail_address"
                android:textColor="@color/isparkDetailText"
                android:singleLine="false"
                android:layout_marginLeft="@dimen/abc_action_bar_subtitle_bottom_margin_material"
                android:gravity="start"
                android:layout_gravity="center_horizontal" />

        </LinearLayout>

    </LinearLayout>

    <TextView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material"
        android:text=""
        android:singleLine="false"
        android:id="@+id/ispark_detail_location"
        android:layout_gravity="center_horizontal" />

    <LinearLayout
        android:orientation="horizontal"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material">

        <RelativeLayout
            android:id="@+id/relativeLayout1"
            android:layout_width="fill_parent"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/abc_action_bar_subtitle_bottom_margin_material">

            <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:text="@string/close"
                android:layout_alignParentLeft="true"
                android:id="@+id/ispark_detail_cancel"
                android:textColor="@color/isparkDetailButtonCloseText"
                android:background="@android:color/transparent" />

            <Button
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_alignParentRight="true"
                android:text="@string/ispark_detail_route"
                android:id="@+id/ispark_detail_route"
                android:textColor="#FFF"
                android:background="@color/isparkDetailButtonBgActive" />

        </RelativeLayout>

    </LinearLayout>
    </LinearLayout>
