### ISSUE TITLE
DialogPlus.ScreenType.FULL doesnt exist

### ISSUE THREAD

**Issue by droweed** [orhanobut/dialogplus#49]
I've checked DialogPlus class and it doesn't seem to exist? or did I miss something

**Comment by orhanobut** [comment]
This is removed unfortunately due to some big issues, instead I'll provide another method which you can decide on the height, wrap, match parent or any custom height

**Comment by droweed** [comment]
ok nice, I'll check on the source on how you manage its layout, and maybe add it myself

**Comment by orhanobut** [comment]
That would be great if you make a pull request for that. :+1:

**Comment by orhanobut** [comment]
Added custom size methods to enable full screen.

```java
.setContentHeight(ViewGroup.LayoutParams.MATCH_PARENT);
.setContentWidth(ViewGroup.LayoutParams.MATCH_PARENT);
```
