### ISSUE TITLE
Using Fragments within dialog

### ISSUE THREAD

**Issue by jomendoz** [orhanobut/dialogplus#50]
Hello,

Is there a way to use Fragments within the dialog?

I've been trying to add a view with a FrameLayout element and calling FragmentManager methods to fetch and change views but it says something about IllegalStateException, view has already a parent or something like that.

I'm trying to make a dialog with tabs...

I went for TabHost but I got different problems with deprecated classes.
I went for ViewPager and PagerTabStrip but it's not the UX I was required to implement.
So I decided to make all by hand with Fragments but I cannot communicate with a FrameLayout for content within your dialog. The FragmentManager mess up with the hierarchy I think...

I'd appreciate any clues about this issue.

**Comment by orhanobut** [comment]
DialogPlus is meant to use for simple cases, in your case if the content is not so complex, maybe you can imitate the tab selection manually by yourself. You can directly pass the resource id to dialogplus and access the views.

**Comment by jomendoz** [comment]
How can I access a FrameLayout within the view attached with ViewHolder? Last time a tryed it came a IllegalStateException trying to attach a fresh new Fragment into de FrameLayout within the layout saying it already has a parent...

This requirement has been so harsh to implement... I'm opting to do it almost all manually. I'd like to know if there is any resource of yours explaning the logic behind the use of Fragments in DialogPlus. Maybe I can reuse most of your code but I'm not such a seasoned Android developer...

**Comment by jomendoz** [comment]
Here is pair of screenshot with what I am supposed to replicate:

![teclado-gh1](https://cloud.githubusercontent.com/assets/10285345/8477849/fc06a112-2092-11e5-8398-35359533e6f7.png)

![teclado-gh2](https://cloud.githubusercontent.com/assets/10285345/8477852/ff6eb4c0-2092-11e5-8fe0-d865be0e670d.png)

**Comment by jomendoz** [comment]
Since tabs are fixed there is no problem catching their click events. The problem is replacing the frame where the NumberPickers are...

That blue background is the calling Activity (but just cropped).

**Comment by orhanobut** [comment]
Assuming that your layout is R.layout.dialog and you set it like below.
```java
dialog.setContentHolder(new ViewHolder(R.layout.dialog))
```

you can get it back by using
```java
dialog.getHolderView();  //this will return the inflater layout
```

you can also get specific views by using findViewById
```java
dialog.findViewById(R.id.header_text)
```

**Comment by jomendoz** [comment]
Thank you. I ended up hidding and showing subviews in the main view with View.GONE and View.VISIBLE.

I know it's not the most elegant solution but it does the job just fine.

What a nightmare has been trying to add tabs to a dialog. Closing issue.
