### ISSUE TITLE
Dialog on tablet issue

### ISSUE THREAD

**Issue by Kpeved** [orhanobut/dialogplus#51]
I have an issue with dialog on tablets - it stretches on all screen instead of fixed size. Is it possible to set fixed width to it ? 
![screen shot 2015-07-07 at 12 46 22 pm](https://cloud.githubusercontent.com/assets/8842917/8543575/4d950da4-24a6-11e5-9cf4-f0ae07585f22.png)

**Comment by orhanobut** [comment]
That's a good idea, I added it to the backlog

**Comment by orhanobut** [comment]
Added a new option to set width and height manually.
```java
.setContentWidth
.setContentHeight
```
