### ISSUE TITLE
setHeader() and setFooter() set wrong views

### ISSUE THREAD

**Issue by evgenyh** [orhanobut/dialogplus#60]
view passet to setHeader() method in DialogPlus.newDialog(context) builder object
actually appears as footer. And view passet to setFooter() appears as header.
version 1.9

bug in DialogPlus class. line line 181
private View createView(LayoutInflater inflater, View footerView, View headerView, BaseAdapter adapter)

params View footerView, View headerView are misplaced

**Comment by orhanobut** [comment]
This is fixed but not released yet. Next version will have this fix.

**Comment by evgenyh** [comment]
Yes just saw it.
Can you process a minor release ? like 1.9.1

As I'm waiting for this to release my apk

**Comment by orhanobut** [comment]
Today I'll release a fixed version.

**Comment by orhanobut** [comment]
v1.10 is released but will be available in 10 min
