### ISSUE TITLE
setHeader() and setFooter() in big lists

### ISSUE THREAD

**Issue by jcmmagnusson** [orhanobut/dialogplus#61]
I would like the header and footer to always be visible. Right now, in a big list, you have to scroll to the bottom to find the footer (containing cancel, accept, etc buttons), which feels wrong. 

Also, because of this implementation (I suppose), they do not show up if I use the GridHolder.

Do I have to use a custom ViewHolder for the behavior I want?

**Comment by orhanobut** [comment]
That's a good idea, we can introduce an optional parameter while setting header and footer
```java
.setHeader(view, true);
```

**Comment by androidexceptioncom** [comment]
Yeah very good idea

**Comment by pointblankcoder** [comment]
I agree, this would be a great addition. Something I expected to happen and realized it's not. For now I'm showing my action buttons at the top of my content. Feels a little awkward.

**Comment by hnvn** [comment]
I can't wait for this new feature. When do you release this feature?
