### ISSUE TITLE
Gravity.bottom seems not to work

### ISSUE THREAD

**Issue by FrabornaChen** [orhanobut/dialogplus#62]
hi, i ran the sample in genymotion and clicked the bottom button, but it turns out like this
![image](https://cloud.githubusercontent.com/assets/2952908/8888962/8bd815da-32f6-11e5-9202-2b1d97250863.png)
clicking the space under the dialog could not dismiss the dialog,
rather than clicking the space above it.

i ran it in my android testing machine, and came across the same problem

**Comment by orhanobut** [comment]
I use the sample for experimental things, if you check the sample builder, height is set to 800 for test purpose. This is totally ok.
