### ISSUE TITLE
 Don't call setOnClickListener for an AdapterView. You probably want setOnItemClickListener instead

### ISSUE THREAD

**Issue by wood23636** [orhanobut/dialogplus#63]
Hi, I want to add a whellview to dialogplus, it extend from spinner. but throw a exception. 

07-25 22:13:30.493: E/AndroidRuntime(13740): java.lang.RuntimeException: Don't call setOnClickListener for an AdapterView. You probably want setOnItemClickListener instead
07-25 22:13:30.493: E/AndroidRuntime(13740): 	at com.jyxtec.wheel.TosAdapterView.setOnClickListener(TosAdapterView.java:803)
07-25 22:13:30.493: E/AndroidRuntime(13740): 	at com.orhanobut.dialogplus.DialogPlus.setClickListener(DialogPlus.java:315)
07-25 22:13:30.493: E/AndroidRuntime(13740): 	at com.orhanobut.dialogplus.DialogPlus.assignClickListenerRecursively(DialogPlus.java:300)
07-25 22:13:30.493: E/AndroidRuntime(13740): 	at com.orhanobut.dialogplus.DialogPlus.assignClickListenerRecursively(DialogPlus.java:297)
07-25 22:13:30.493: E/AndroidRuntime(13740): 	at com.orhanobut.dialogplus.DialogPlus.assignClickListenerRecursively(DialogPlus.java:297)
07-25 22:13:30.493: E/AndroidRuntime(13740): 	at com.orhanobut.dialogplus.DialogPlus.assignClickListenerRecursively(DialogPlus.java:297)
07-25 22:13:30.493: E/AndroidRuntime(13740): 	at com.orhanobut.dialogplus.DialogPlus.assignClickListenerRecursively(DialogPlus.java:297)
07-25 22:13:30.493: E/AndroidRuntime(13740): 	at com.orhanobut.dialogplus.DialogPlus.createView(DialogPlus.java:259)
07-25 22:13:30.493: E/AndroidRuntime(13740): 	at com.orhanobut.dialogplus.DialogPlus.initContentView(DialogPlus.java:227)
07-25 22:13:30.493: E/AndroidRuntime(13740): 	at com.orhanobut.dialogplus.DialogPlus.<init>(DialogPlus.java:111)
07-25 22:13:30.493: E/AndroidRuntime(13740): 	at com.orhanobut.dialogplus.DialogPlusBuilder.create(DialogPlusBuilder.java:265)

**Comment by wood23636** [comment]
version 1.10

**Comment by orhanobut** [comment]
can you show the whole implementation of dialogplus?

**Comment by wood23636** [comment]
WheelView monthWheel = (WheelView)viewGroup.findViewById(R.id.month_wheel);
//
//
//
                monthWheel.setScrollCycle(true);
                NumberAdapter monthAdapter = new NumberAdapter(monthArray);
                monthWheel.setAdapter(monthAdapter);
                monthWheel.setOnItemSelectedListener(mWheelViewListener);
                monthWheel.setUnselectedAlpha(0.5f);
                monthWheel.setOnItemClickListener(new TosAdapterView.OnItemClickListener() {
                    @Override
                    public void onItemClick(TosAdapterView<?> tosAdapterView, View view, int i, long l) {

                    }
                });

                DialogPlus dialogPlus = DialogPlus.newDialog(getActivity())
                        .setContentHolder(new ViewHolder(viewGroup))
                        .setGravity(Gravity.BOTTOM)
                        .setCancelable(true)
                        .setOnItemClickListener(new OnItemClickListener() {
                            @Override
                            public void onItemClick(DialogPlus dialogPlus, Object o, View view, int i) {

                            }
                        })
                        .create();
                dialogPlus.show();

**Comment by orhanobut** [comment]
When you use ViewHolder, you can't use OnItemClickListener, if you want to have click events of the individual views, use OnClickListener, or if you already handle it by yourself, just remove all click listeners from dialogplus.

**Comment by wood23636** [comment]
yes I have removed all click listeners before. But it throw the exception too. 
```java
DialogPlus dialogPlus = DialogPlus.newDialog(getActivity())
                        .setContentHolder(new ViewHolder(viewGroup))
                        .setGravity(Gravity.BOTTOM)
                        .setCancelable(true)
                        .create();
                dialogPlus.show();
```

**Comment by wood23636** [comment]
I think that, when I give a custom viewgroup, the dialogplus also set the click event all children. But when I set a spinner in it. spinner can not set click event. android throw a exception. Can I forbidden the click event?

**Comment by orhanobut** [comment]
Yes, it seems this is the exact reason and unfortunately there is no this option, but we should add this for these situations. You can only avoid this by creating spinner dynamically, dialogplus adds clicklistener only if the view has an id.

**Comment by wood23636** [comment]
oh! may be I can remove the id and try find it by the tag or parent find chid?

**Comment by orhanobut** [comment]
That could also work but out of box, we already avoid to set clicklistener for adapterview. Need to check thorougly for this issue.

**Comment by wood23636** [comment]
ok. I try to remove the id and get it work. Thanks.

**Comment by orhanobut** [comment]
cheers :+1:

**Comment by bigggge** [comment]
@wood23636 Can you show me your code,I can't solve it, Thanks.

**Comment by Djek-grif** [comment]
In my case I try to add onClickListener for spinner and I've got the same problem. I've crated workaround with touch listener: 

someSpinner.setOnTouchListener { _, event ->  onTouchSomeSpinner(event)}
    
    fun onTouchSomeSpinner(event: MotionEvent): Boolean {
            if(event.action == MotionEvent.ACTION_UP) {
                view.hideKeyBoard()
                view.analyticsEvent()
                ...
            }
            return false
        }
