### ISSUE TITLE
Transparent black background can not be removed

### ISSUE THREAD

**Issue by ergunkocak** [orhanobut/dialogplus#70]
Hello,

Even i used : 

``` java
setBackgroundColorResourceId(R.color.transparent_color)
```

there is still a transparent background i could change it like this : 

``` java
((FrameLayout) findViewById(R.id.content_container).getParent()).setBackgroundColor(getResources().getColor(R.color.transparent_color))
```

FYI

**Comment by orhanobut** [comment]
@ergunkocak backgroundcolor is used for the content, not for the transparent black overlay. But we can add this feature, or contribute is also very welcome :)

**Comment by ergunkocak** [comment]
ok this is on me than :) I will contribute asap

**Comment by orhanobut** [comment]
:+1:

**Comment by orhanobut** [comment]
I have added a method to change the overlay background resource. for example:
`setOverlayBackgroundResource(R.color.transparent)`

**Comment by orhanobut** [comment]
Closing this issue since it can be done via new method. 👍
