### ISSUE TITLE
Cannot open dialog straight after closing another one?

### ISSUE THREAD

**Issue by broakenmedia** [orhanobut/dialogplus#76]
I have a function, which on success shows a dialog. However, if there is an error it will show a different dialog. If they press "OK" on the error dialog the function is recursively called and now ends in success. However the other dialog will not show, it's almost as if the old dialog isnt being dismissed in time.

**Comment by orhanobut** [comment]
thanks for the reporting this, let me check it.

**Comment by xbroak** [comment]
Any news on this? :)

**Comment by xbroak** [comment]
/**
   * It adds the dialog view into rootView which is decorView of activity
   */
  public void show() {
    if (isShowing()) {
      return;
    }
    onAttached(rootView);
  }

  /**
   * It basically check if the rootView contains the dialog plus view.
   *
   * @return true if it contains
   */
  public boolean isShowing() {
    View view = decorView.findViewById(R.id.outmost_container);
    return view != null;
  }

Looks like it's finding the same outmost_container when trying to open a new dialog and returning

**Comment by orhanobut** [comment]
The problem lays in the animation duration actually, we need to differentiate for each instance. By the way, sorry I couldn't have enough time to check this issue

**Comment by xbroak** [comment]
I'm assuming the isShowing will only return false once the dismiss animation as ended for the previous dialog?

**Comment by xbroak** [comment]
No problem! I've gotta try and figure out a solution asap though!

**Comment by orhanobut** [comment]
A work around would be to use dismiss listener and show the second dialog

**Comment by xbroak** [comment]
I was thinking the same thing, however the action needs to be taken based on the option chosen in the first dialog i.e. "If YES" on dismiss try again, otherwise do nothing" I can probably do this with some awkward boolean switches though

**Comment by HectorFGarcia** [comment]
I have the same problem. As #1 is pointing out, It seems like the first dialog doesn't dismiss in time so the second one doesn't show up.

**Comment by fnoori** [comment]
Any update on this bug?
Following your suggestion for opening the new dialogPlus in the "OnDismiss" listener, that will open the new dialog if the user taps outside the first dialog as well. Any way to prevent this from happening? 
This is an awesome library by the way !!

**Comment by orhanobut** [comment]
The issue can be solved by work around via using dismissListener for now.

**Comment by pellyadolfo** [comment]
ugly but works

**Comment by orhanobut** [comment]
Closing this issue due to long time period, can reopen if needed

**Comment by KopiHitam** [comment]
AFAIK there's only one dialog can be shown at once, is it possible to put static function to check whether any dialog shown or not?
