### ISSUE TITLE
Show panel in bottom centre

### ISSUE THREAD

**Issue by Kisty** [orhanobut/dialogplus#79]
Doing DialogPlusBuilder#setGravity(Gravity.CENTER | Gravity.CENTER_HORIZONTAL) causes a crash because it can't work out the animation to play in #getOutAnimation(). I think it just requires a bit mask check rather than using equals.

**Comment by orhanobut** [comment]
That should work out of box actually, need to check. I'll try to add more tests to cover these situations. Contributions are also very welcome.

**Comment by Kisty** [comment]
OK. So I've managed to get the gravity sorted but now what if I want to show a card, with space either side? Am trying to tinker with the layout params in the DialogPlus class. Any ideas?

**Comment by orhanobut** [comment]
You can use 
```java
.setMargin
//or
.setPadding
```

**Comment by Kisty** [comment]
I know that, but the problem is, is that by default the custom view takes up the whole width of the screen. I want it to show up like a card with transparent space either side. I've changed this in getContentParams so that it uses a separate params object and width param as WRAP_CONTENT rather than MATCH_PARENT. Try changing content2.xml root's height to WRAP_CONTENT and set background resource id to transparent in the sample app to see what I mean. 

It works in my case but breaks everything else. Either we can use the width and height params from the root of the custom view or we could put a switch in to it to say match_parent on the custom view.

**Comment by Kisty** [comment]
This is what I have at the moment:
![device-2015-09-15-094838](https://cloud.githubusercontent.com/assets/3243752/9872095/020ecba2-5b8f-11e5-80f9-43b4dc3971c7.png)

**Comment by orhanobut** [comment]
I get it now, no unfortunately this overlay will be shown all the time, I was expecting to have a PR for this feature to be able to change the background.

**Comment by Kisty** [comment]
Which background? Can't you already change the background. I'd like to show
you what I mean by an example. Is a PR the best way to do that?

**Comment by orhanobut** [comment]
I was assuming that you are talking about the background color with transparency?

**Comment by Kisty** [comment]
No, I didn't mean that only. I can do that easily by using setBackgroundResourceId(android.R.color.transparent). When you do that, it doesn't behave in the way expected. Here's the PR to avoid the crash with a composite gravity #80

**Comment by orhanobut** [comment]
Closing this issue since a merged PR solves the issue.
