### ISSUE TITLE
Conflict with Attribute 'Corner Radius'

### ISSUE THREAD

**Issue by stripathi669** [orhanobut/dialogplus#82]
Hi

I want to report a conflict error:

    AGPBI: {"kind":"ERROR","text":"Attribute \"corner_radius\" has already been defined","sourcePath":"{Path to app}\\app\\build\\intermediates\\exploded-aar\\com.orhanobut\\dialogplus\\1.10\\res\\values\\values.xml","position":{"startLine":1},"original":""}

The conflict is reported for the library: https://github.com/kanytu/ImageWindow

**Comment by orhanobut** [comment]
Thank you. I think best solution would be to change all those public variables by adding a weird prefix

**Comment by orhanobut** [comment]
changed all attributes although there is no "corner_radius" attribute in dialogplus.
