### ISSUE TITLE
how to set multipleSelectItem?

### ISSUE THREAD

**Issue by zhangxiaang** [orhanobut/dialogplus#83]
just like this:
AlertDialog.Builder  d = new AlertDialog.Builder(yourcontext);
d.setMultiChoiceItems(elements, null , new OnMultiChoiceClickListener() {
 @Override
 public void onClick(DialogInterface dialog, int which, boolean isChecked) {
       if(isChecked){
          String str = elements[which];
          Toast.makeText(youractivity.this,
                    "you have selected"+str,
                     Toast.LENGTH_LONG).show();
        }
   }
 });

**Comment by orhanobut** [comment]
There is no multiselect feature unfortunately.

**Comment by orhanobut** [comment]
closing this issue. currently won't support multiselect function unfortunately.
