### ISSUE TITLE
how to get the event after the dialogplus show?

### ISSUE THREAD

**Issue by wood23636** [orhanobut/dialogplus#85]
I want to start a view animation after the dialogplus measure. But I can not get the event. I need to calculate the position and size before the animation start.

**Comment by orhanobut** [comment]
There is no listener for this event unfortunately. Could use a PR for this though.

**Comment by wood23636** [comment]
PR?

**Comment by orhanobut** [comment]
pull request

**Comment by orhanobut** [comment]
Closing this issue due to long time period, can reopen if needed
