### ISSUE TITLE
ClickListener on footer and/or header RecyclerAdapter

### ISSUE THREAD

**Issue by konigsoft** [orhanobut/dialogplus#87]
Hi @orhanobut thank you for you lib but i have two questions;
How to implement clicklistener on a view in footer and or header?[fix to be define after the creation of the dialog]
Do you plan to add recyclerAdapter support for recycler view?

best regards,

**Comment by orhanobut** [comment]
I'm out of city currently, I'll check this issue in a few days

**Comment by orhanobut** [comment]
Hi,

Footer or Header views are treated as normal views. You can either pass view object itself or the resource id. You can access view clicks if they have id.
`setOnClickListener`

**Comment by orhanobut** [comment]
Closing this issue due to long time period, can reopen if needed
