### ISSUE TITLE
setContentHeight but it just change location

### ISSUE THREAD

**Issue by ForgetV** [orhanobut/dialogplus#89]
DialogPlus dialogPlus = DialogPlus.newDialog(context)
                .setContentHolder(new GridHolder(4))
                .setAdapter(adapter)
                .setCancelable(true)
                .setBackgroundColorResourceId(R.color.White)
                .setGravity(Gravity.BOTTOM)
                .setContentHeight(ViewGroup.LayoutParams.MATCH_PARENT)
                .create();
the result is the views looks dialog setGravity(Gravity.TOP) the background color is not fill with what I set.

**Comment by orhanobut** [comment]
Closing this issue due to long time period, can reopen if needed
