### ISSUE TITLE
change overlay_color like scrim color in Navigation Drawer

### ISSUE THREAD

**Issue by akashk1992** [orhanobut/dialogplus#95]
when we open the the dialog (eg : no footer), it dim's the whole activity Overlay color to some what  semi-transparent black but I want "No-Color" or "completely transparent" there. how can I do it?

**Comment by orhanobut** [comment]
I'll add this feature

**Comment by orhanobut** [comment]
with 1.11, you can use the following method to change overlay background. for example:
`.setOverlayBackgroundResource(R.color.transparent)`

**Comment by akashk1992** [comment]
thanx for the reply it worked
