### ISSUE TITLE
How to Set corner for dialog ?

### ISSUE THREAD

**Issue by chihung93** [orhanobut/dialogplus#97]
Hello 
I want to set the corner for dialog but is not work? I have tried many ways but failed as set xml , GradientDrawable with DialogUpgrade.getHolderView ( ),and customize layout of View
tks .
Please help me

**Comment by orhanobut** [comment]
Hi,

You can create a shape with corners and pass it to the dialogplus.

`setContentBackgroundResource(R.drawable.rounded_background)`

**Comment by trihung93** [comment]
tks , very useful 
have a nice day ^^

**Comment by trihung93** [comment]
But its just work when i seleced Show header or Show footer  , or Showheader and footer
this is new bug on this library 
Tks

**Comment by orhanobut** [comment]
Closing this issue due to long time period, can reopen if needed

**Comment by windfone** [comment]
![1581416854(1)](https://user-images.githubusercontent.com/40689038/74228784-1cfc7c80-4cfc-11ea-9734-8d29634fbb93.png)
setContentBackgroundResource does not work

**Comment by windfone** [comment]
`WindowManager windowManager = (WindowManager) this
                .getSystemService(Context.WINDOW_SERVICE);
        Display display = windowManager.getDefaultDisplay();

        DialogPlus dialogPlus = DialogPlus.newDialog(this)
                .setGravity(Gravity.CENTER)
                .setContentHolder(new ViewHolder(R.layout.dialog_net))
                .setContentWidth((int) (display
                        .getWidth() * 0.8))
                .setContentBackgroundResource(R.drawable.shape_radius_4dp)
                .setContentHeight(LinearLayout.LayoutParams.WRAP_CONTENT)
                .setCancelable(true)
                .setOnClickListener((dialog, view1) -> {
                    switch (view1.getId()) {
                        case R.id.confirm_btn:
                            dialog.dismiss();
                            break;
                    }
                }).create();
        dialogPlus.show();`

**Comment by windfone** [comment]
oh,i see, can't set background in xml root point, otherwise it will be invalid
